
source 'https://rubygems.org'

gem 'gemoji'
gem 'faraday'
gem 'textmood'
gem 'discordrb'
gem 'rest-client'
gem 'mime-types'
gem 'paho-mqtt'
gem 'erb'
gem 'json'
gem 'sinatra'
gem 'date'
gem 'wikipedia-client'
gem 'eqn'
gem 'digest'
gem 'redi_search'
gem 'bigdecimal'
gem 'minitest'
gem 'activesupport'
gem 'zeitwerk'
gem 'redis'
gem 'redis-objects'
gem 'connection_pool'
gem 'rackup'
