#!/bin/bash

trap "exit" INT TERM ERR
trap "kill 0" EXIT

if [[ "$1" == "nomad" ]]; then
    sudo ./exe/nomad.sh
elif [[ "$1" == "setup" ]]; then
    ./bin/setup
else
    source env.sh

    inotifywait -m -e CLOSE_WRITE --format '%T %w %f %e' --timefmt '%Y-%m-%dT%H:%M:%S' org | while \
	read datetime dir filename event; do
	if [[ $filename == *.org ]]; then
	    echo "INOTIFYWAIT: $datetime $dir $filename $event"
	    cd $dir
	    x=`echo "$filename" | awk '{ gsub(".org", ".html") ; system( "echo "  $0) }'`
	    org-export html --infile $filename --outfile ../html/$x --css-name orgcss
	    #	git add .
	    #	git commit -m "update in $filename at $datetime"
	    cd ..
	fi
    done &
    
    ruby bin/console
fi

wait
