#!/bin/bash

rm *~ */*~ */*/*~
rm *# */*# */*/*#

if [[ "$1" == "--kill" ]]; then
    sudo pkill ruby && sudo pkill redis

elif [[ "$1" == "--setup" ]]; then
    ./exe/z4

elif [[ "$1" == "--headless" ]]; then
    ./exe/server
else
    ./exe/client
fi

exit 0;
