#!/bin/bash

##
#
# The Z4 Container
#
# A containerized instance of the z4 system.
#
# 1. install packages.
# 2. install gems.
# 1. create user ~/.screenrc.
# 2. create nomad executable.
# 3. create ~/.nomad script.
# 4. install executable.
#
##

source env.sh

D=/etc/skel

apt install screen ruby ruby-dev build-essential mosquitto libffi-dev libssl-dev fuse $EDITOR

gem install gemoji faraday textmood discordrb paho-mqtt erb json sinatra date wikipedia-client eqn digest redi_search redis-objects connection_pool rackup

# Create local screenrc.
cat <<EOF>$D/.screenrc
shell -/bin/bash
caption always "[ %H ] %w"
defscrollback 1024
startup_message off
hardstatus on
hardstatus alwayslastline
screen -t '#' 0 emacs -nw --funcall erc --visit ~/index.org
screen -t '>' 1 /bin/bash
select 1
EOF

# construct bash shell layer
cat << EOF > $D/.nomad
# simplify lan scanning
function lan() {
    IP_REGEXP="(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
    IPs=\$(sudo arp-scan --localnet | grep -E -o \$IP_REGEXP)
    sudo nmap -O -F -v \$IPs
}
# load ruby rvm
export PATH="\$PATH:\$HOME/.rvm/bin"
source ~/.rvm/scripts/rvm
source /home/\$USER/.rvm/scripts/rvm
# simplify push process.
function commit() {
 source github.sh
 git remote set-url origin https://\$user:\$token@github.com/\$user/\$repo.git;
 git add .
 git commit -m "\$1"
 git push
}
# pipx path
export PATH="\$PATH:/home/\$USER/.local/bin"
# git aware prompt. (pretty)
export PS1='\${debian_chroot:+(\$debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[01;33m\]\$(__git_ps1)\[\033[00m\]\$ ';
echo "##### LOADED WITH NOMADIC CAPABILITIES #####"
EOF

echo 'source ~/.nomad' >> $D/.bashrc

echo '(screen -Dr || screen)' > /usr/bin/nomad
chmod 007 /usr/bin/nomad

exit 0;
