#!/bin/bash

# url for iso torrent
torrent='https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-12.4.0-amd64-netinst.iso.torrent'
# iso name when downloaded
iso='debian-12.4.0-amd64-netinst.iso'
# iso torrent filename
f=debian.torrent
# file for vm hda
i=z4.img
# amount of ram allocated to vm
ram='1024M';
# max size of vm image
size='2G';





# fetch <bin> <url>
function fetch() {
    wget -O $1 -c $2
}

# install <bin>
function install() {
    sudo cp -vv $1 /usr/sbin/$2
}





##
# DOWNLOAD BASE INSTALLER
if [[ ! -f $f ]]; then
    wget -O $f -c $iso && ctorrent $f;
fi





##
# CREATE Z4 ENVIROMENT
if [[ ! -f $i ]]; then
    sudo apt install qemu-kvm qemu-system qemu-utils python3 python3-pip libvirt-clients libvirt-daemon-system bridge-utils virtinst libvirt-daemon virt-manager -y
    sudo systemctl restart libvirtd.service
    sudo virsh net-start default
    sudo virsh net-autostart default
    sudo usermod -aG libvirt $USER
    sudo usermod -aG libvirt-qemu $USER
    sudo usermod -aG kvm $USER
    sudo usermod -aG input $USER
    sudo usermod -aG disk $USER
    qemu-img create -f qcow2 $i $size
    qemu-system-x86_64 -net nic -net user -m $ram -hda $i -drive file=$iso,media=cdrom -boot c
fi





##
# RUN VM
if [[ "$2" == "--vnc" ]]; then
    qemu-system-x86_64 -nodisplay -net nic -net user -m $ram -hda $i -vnc :0
else
    qemu-system-x86_64 -net nic -net user -m $ram -hda $i
fi

exit 0;
