#!/bin/bash

##
#
# The Z4 System
#
# - A simple wrapper around a local vector database and llamafile
#
# 1. install system utilities
# 1.1 install gui?
# 1.2 install remote gui?
# 2. install rvm stable ruby for discord bot and web app.
# 3. install redis-stack noSQL database with vector extensions.
# 4. install llamafile.
# 6. x11, window manager, vnc.
# 7. crontab
#
##

sudo ./exe/nomad

source env.sh

if [[ -z "$WM" ]]; then
    
    Z4_TASK_IOT='kicad'
    Z4_TASK_STREAM='pitivi kdenlive obs beep audacity autoradio'
    
    Z4="xinit xorg $TERMINAL $WM"
    
    if [[ -z "$IOT" ]]; then
	Z4+=$Z4_TASK_IOT
    fi
    
    if [[ -z "$STREAM" ]]; then
	Z4+=$Z4_TASK_STREAM
    fi
    
    sudo apt install $Z4_XORG -y
    
fi

# write z4 crontab
echo '@reboot $(cd ~/z4 && ./z4 --headless)' > mc
crontab mc
rm mc

exit 0;
